import Hero from '@/pages/Hero'
import { Signika } from 'next/font/google'
import '../globals.css'

const signika = Signika({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={signika.className}>
      <body>
        <Hero />
        {children}
      </body>
    </html>
  )
}
